[tool.poetry]
name = "langchain-openai-api-bridge"
version = "0.1.0"
description = "A bridge to use Langchain output as an OpenAI-compatible API."
authors = ["Samuel Magny <samuelint@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.2.2"
langchain-openai = "^0.1.8"


[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^0.23.7"
pytest = "^8.2.2"
pytest-watch = "^4.2.0"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
