name: Publish to PyPI

env:
  PYPI_PACKAGE_NAME: langchain_openai_api_bridge
on:
  release:
    types:
      - created

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: ["build"]
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: artifact/
